#---
#- name: Deploy SciCalc Docker container
#  hosts: local
#  become: yes
#  tasks:
#    - name: Pull latest Docker image from Docker Hub
#      command: docker pull aryanvaghasiya/scicalc-app:latest
#
#    - name: Stop and remove existing SciCalc container (if running)
#      command: docker rm -f scicalc-app
#      ignore_errors: yes
#
#    - name: Run SciCalc container
#      command: docker run -d --name scicalc-app aryanvaghasiya/scicalc-app:latest
#
---
- name: Deploy SciCalc Docker container
  hosts: local 
  become: yes
  tasks:
    # 1. Ensure the Python 'docker' package is installed
    - name: Ensure Python 'docker' package is installed
      ansible.builtin.pip:
        name: docker
        state: present

    # 2. Deploy and manage SciCalc container
    - name: Deploy and manage SciCalc container from Docker Hub
      community.docker.docker_container:
        name: scicalc-app
        image: aryanvaghasiya/scicalc-app:latest
        state: started
        
        # Pull latest image and force recreation
        pull: yes 
        recreate: yes 
        
        # --- CORRECTION APPLIED HERE (Changed Host Port to 9000) ---
        # Map container port 80 to host port 9000
        ports:
          - "9000:80"
          
        restart_policy: always

